config/routes.rb
Multiupload::Application.routes.draw do
  resources :buckets do
		resources :assets
	end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
	has_attached_file :data, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_presence :data
	
	belongs_to :attachable, :polymorphic => true
	
	before_post_process :is_image?
	def is_image?
	  !(self.data.content_type =~ /^image/).nil?
	end
end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
	has_many :assets, :as => :attachable
	accepts_nested_attributes_for :assets, :allow_destroy => true, :reject_if => lambda { |a| a[:data].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
	
	before_filter :bucket
	
	
	# GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to bucket_asset_path(@bucket, @asset), notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to bucket_asset_path(@bucket, @asset), notice: 'Asset was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to bucket_assets_url(@bucket) }
      format.json { head :ok }
    end
  end

	protected
	
	def bucket
		@bucket = Bucket.find(params[:bucket_id])
	end
	
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
	before_filter :only => [:update, :create] do |c|
		c.params[:bucket] = MultipleFileUploadFilter.map_multiple_uploads(c.params[:bucket])
	end
	
  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buckets }
    end
  end

  # GET /buckets/1
  # GET /buckets/1.json
  def show
    @bucket = Bucket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bucket }
    end
  end

  # GET /buckets/new
  # GET /buckets/new.json
  def new
    @bucket = Bucket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bucket }
    end
  end

  # GET /buckets/1/edit
  def edit
    @bucket = Bucket.find(params[:id])
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(params[:bucket])

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
        format.json { render json: @bucket, status: :created, location: @bucket }
      else
        format.html { render action: "new" }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buckets/1
  # PUT /buckets/1.json
  def update
    @bucket = Bucket.find(params[:id])

    respond_to do |format|
      if @bucket.update_attributes(params[:bucket])
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket = Bucket.find(params[:id])
    @bucket.destroy

    respond_to do |format|
      format.html { redirect_to buckets_url }
      format.json { head :ok }
    end
  end

	protected
	
	def extract_multiple_assets
		if params[:bucket][:assets_attributes]
			
		end
		
		return true
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/assets/_asset.html.haml
%section[asset]
  = asset.data_file_name
  \|
  = asset.data_content_type
  \|
  = asset.data_file_size

app/views/assets/_form.html.haml
= form_for [@bucket, @asset]  do |f|
  -if @asset.errors.any?
    #error_explanation
      %h2= "#{pluralize(@asset.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend Upload an image
    .field.clearfix
      = f.label :source
      .input
        = f.file_field :data
        %span.help-block jpgs, pngs, bmps, and gifs allowed.
  
  .actions
    = f.submit 'Save'

app/views/assets/index.html.haml
%h1 Assets

= render @assets

\|

%p
  = link_to 'New Asset', new_bucket_asset_path(@bucket)

app/views/assets/new.html.haml
%h1 New asset

= render 'form'

= link_to 'Back', bucket_assets_path(@bucket, @asset)

app/views/assets/show.html.haml
%h1 Asset

= render @asset

\|
= link_to "Assets", bucket_assets_path(@bucket)

app/views/buckets/_asset_fields.html.haml
.field
  %legend= f.object.data_file_name
  = f.label :_destroy
  = f.check_box :_destroy

app/views/buckets/_form.html.haml
= form_for @bucket do |f|
  -if @bucket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bucket.errors.count, "error")} prohibited this bucket from being saved:"
      %ul
        - @bucket.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    %legend Assets
    = f.fields_for :assets do |asset_f|
      = render "asset_fields", :f => asset_f

    = f.fields_for :assets, @bucket.assets.build do |asset_f|
      #dropbox.dropbox
        %span Drop your files here to upload them
      
      = asset_f.label :data, "Upload a file"
      = asset_f.file_field :data, :class => 'file_input', :multiple => true
      
      #bag
        %span Files
      
  .actions
    = f.submit 'Save'

app/views/buckets/edit.html.haml
%h1 Editing bucket

= render 'form'

= link_to 'Show', @bucket
\|
= link_to 'Back', buckets_path

app/views/buckets/index.html.haml
%h1 Listing buckets

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @buckets.each do |bucket|
    %tr
      %td= bucket.name
      %td= link_to 'Show', bucket
      %td= link_to 'Edit', edit_bucket_path(bucket)
      %td= link_to 'Destroy', bucket, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Bucket', new_bucket_path

app/views/buckets/new.html.haml
%h1 New bucket

= render 'form'

= link_to 'Back', buckets_path

app/views/buckets/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bucket.name
  
%p
  %b Assets
  = render @bucket.assets

= link_to 'Edit', edit_bucket_path(@bucket)
\|
= link_to 'Back', buckets_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multiupload</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div id="header" class="container sidebar">
		<%= yield :header %>
	</div>
	<div class="content">
		<%= yield %>
	</div>

</body>
</html>